name: Open Banking Backend

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - dev
  
jobs:
  docker-steps:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.2.21
        ports:
          - "27017:27017"
      postgres:
        image: postgres:10.21-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: circle_test
      golang:
        image: golang:1.17-alpine3.15
        ports:
          - "8080:8080"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Log Env Variables
        run: |
          echo "Logging Environment Variables"
          echo "============="
          echo "Present Working Directory: $(pwd)"
          echo "Present Working Directory: $(pwd -P)"
          echo "GOROOT: ${GOROOT}"
          echo "GOPATH: ${GOPATH}"
          export GOBIN=$GOPATH/bin
          echo "GOBIN: ${GOBIN}"
          export PATH=$PATH:$GOBIN
          ls -latr $GOROOT
          ls -latr $GOPATH
          ls -latr $GOBIN
          go env
          echo "============="
          sh run.sh 
      - name: Install Dockerize
        run: |
          wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        env:
          DOCKERIZE_VERSION: v0.3.0