name: Open Banking Backend

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - dev
  
jobs:
  docker-steps:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.2.21
        ports:
          - "27017:27017"
      postgres:
        image: postgres:10.21-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: circle_test
      golang:
        image: golang:1.17-alpine3.15
        ports:
          - "8080:8080"
    steps:
      - name: Change Working Directory
        run: |
          echo "Changing Working Directory"
          cd
          mkdir circle-ci-lambda
          pwd
        working-directory: circle-ci-lambda
      - name: Checkout
        uses: actions/checkout@v1
      - name: Log Env Variables
        run: |
          echo "Logging Environment Variables"
          echo "============="
          pwd
          pwd -P
          echo $GOROOT
          echo $GOPATH
          export GOBIN=$GOPATH/bin
          echo $GOBIN
          export PATH=$PATH:$GOBIN
          ls -latr $GOROOT
          ls -latr $GOPATH
          ls -latr $GOBIN
          go env
          echo "============="